# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/language-java/
version: 2.1

orbs:
  azure-acr: circleci/azure-acr@0.2.1
  azure-aks: circleci/azure-aks@0.3.0

executors:
  my-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: /tmp/workspace

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#docker-machine-macos-windows-executor
    executor: my-executor

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      - run: ./gradlew build -x test

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: /tmp
          # Must be relative path from root
          paths:
            - workspace

  test:
    executor: my-executor
    
    steps:
      - attach_workspace:
      # Must be absolute path or relative path from working_directory
          at: /tmp
      # run tests!
      - run: ./gradlew test
      
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
          
      - store_test_results:
          path: ~/test-results



workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - approval:
          type: approval
          requires:
            - test
      - azure-acr/build-and-push-image:
          requires:
            - approval
          alternate-tenant: false 
          attach-workspace: true
          workspace-root: /tmp
          path: /tmp/workspace 
          login-server-name: pswacr.azurecr.io 
          registry-name: pswacr 
          repo: spring-demo-app
          tag: $CIRCLE_WORKFLOW_ID
          context: org-global
      - azure-aks/update-container-image:
          requires:
            - azure-acr/build-and-push-image
          get-rollout-status: true 
          watch-rollout-status: true 
          cluster-name: psw-kube 
          container-image-updates: spring-demo-app=pswacr.azurecr.io/spring-demo-app:$CIRCLE_WORKFLOW_ID
          get-admin-credentials: false 
          namespace: demo 
          record: false 
          resource-group: psw-kube_group 
          resource-name: deployment/spring-demo-app 
          show-kubectl-command: true 
          subscription: Azure subscription 1 
          executor:
            name: azure-aks/default
            debian-release: buster
          context: org-global